name: flutter_pokedex_app
packages:
  - "app/**"
  - "packages/**"

command:
  bootstrap:
    usePubspecOverrides: true

scripts:
  analyze:
    exec: flutter analyze

  format:
    exec: flutter format . --set-exit-if-changed

  test:
    exec: flutter test

  clean:
    exec: flutter clean

  generate:flutter:
    exec: flutter pub run build_runner build --delete-conflicting-outputs
