name: auth
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.3.4 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  riverpod_annotation: ^2.3.5
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  riverpod: ^2.5.1
  hooks_riverpod: ^2.5.1
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10
  core_providers:
    path: '../../core/core_providers'

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  melos: ^6.0.0
  build_runner: ^2.4.9

flutter:
  uses-material-design: true
  assets:
    - assets/pngegg.png

