targets:
  $default:
    builders:
      pokedex|gen_localization:
        generate_for:
          - lib/**/*.dart

builders:
  gen_localization:
    import: "package:pokedex/builders.dart"
    builder_factories: [ "localizationBuilder" ]
    build_extensions: { ".dart": [ ".g.part" ] }
    auto_apply: dependents
    build_to: source
    applies_builders: [ "source_gen|combining_builder" ]
